version: '3.9'

services:
  # guanacoto english app
  priverlabapp:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: priverlabapp
    platform: linux/x86_64
    command: npm run dev
    restart: always
    networks:
      - backend_priverlab
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - 3000:3000
      - 5050:5050
    expose:
      - 3000
      - 5050


networks:
  backend_priverlab:
    external: false
    name: backend_priverlab

